server:
  port: 8082
spring:
  data:
   mongodb: 
    uri: mongodb://localhost:27017
    database: activity_fitness
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
   name: fitness_exchange
  queue: 
    name: activity.queue
  routing:
   key: activity.tracking