server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_user_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
      default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

eureka:
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka/